# SITE CONFIG
baseurl: ""
title: "andrea kao 高沁蘭"
timezone: TIMEZONE

date_format: "%Y-%m-%d"

gems: [jekyll-paginate]
paginate: 8
paginate_path: "/page:num/"

# 3rd party scripts, leave empty to disable
google_analytics: "UA-73098936-1"
disqus_shortname:

# BUILD SETTINGS
markdown: kramdown
# redcarpet:
#   extensions: ["smart", "tables", "with_toc_data"]
permalink: pretty